/**
 * Copyright (c) 2014 Meizu bigertech, All rights reserved.
 * http://www.bigertech.com/
 * @author liuxing
 * @date  14-12-30
 * @description
 *
 * @update by laomu1988
 */

module.exports = {
    /** @update by laomu1988@qq.com
     * http://www.cnblogs.com/forthelichking/p/4506058.html
     * */
    woff   : 'application/font-woff',
    eot    : 'application/octet-stream',
    ttf    : 'application/octet-stream',
    svg    : 'text/xml',
    docx   : 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',

    '323':'text/h323',
    '3g2':'video/3gpp2',
    '3gp2':'video/3gpp2',
    '3gpp':'video/3gpp',
    '7z':'application/x-7z-compressed',
    'aa':'audio/audible',
    'AAC':'audio/aac',
    'aaf':'application/octet-stream',
    'aax':'audio/vnd.audible.aax',
    'ac3':'audio/ac3',
    'aca':'application/octet-stream',
    'accda':'application/msaccess.addin',
    'accdb':'application/msaccess',
    'accdc':'application/msaccess.cab',
    'accde':'application/msaccess',
    'accdr':'application/msaccess.runtime',
    'accdt':'application/msaccess',
    'accdw':'application/msaccess.webapplication',
    'accft':'application/msaccess.ftemplate',
    'acx':'application/internet-property-stream',
    'AddIn':'text/xml',
    'ade':'application/msaccess',
    'adobebridge':'application/x-bridge-url',
    'adp':'application/msaccess',
    'ADT':'audio/vnd.dlna.adts',
    'ADTS':'audio/aac',
    'afm':'application/octet-stream',
    'air':'application/vnd.adobe.air-application-installer-package+zip',
    'amc':'application/x-mpeg',
    'application':'application/x-ms-application',
    'art':'image/x-jg',
    'asa':'application/xml',
    'asax':'application/xml',
    'ascx':'application/xml',
    'asd':'application/octet-stream',
    'asf':'video/x-ms-asf',
    'ashx':'application/xml',
    'asi':'application/octet-stream',
    'asm':'text/plain',
    'asmx':'application/xml',
    'aspx':'application/xml',
    'asr':'video/x-ms-asf',
    'asx':'video/x-ms-asf',
    'atom':'application/atom+xml',
    'axs':'application/olescript',
    'bas':'text/plain',
    'c':'text/plain',
    'cab':'application/octet-stream',
    'caf':'audio/x-caf',
    'calx':'application/vnd.ms-office.calx',
    'cat':'application/vnd.ms-pki.seccat',
    'cc':'text/plain',
    'cd':'text/plain',
    'cdda':'audio/aiff',
    'cer':'application/x-x509-ca-cert',
    'chm':'application/octet-stream',
    'clp':'application/x-msclip',
    'cmx':'image/x-cmx',
    'cnf':'text/plain',
    'cod':'image/cis-cod',
    'config':'application/xml',
    'contact':'text/x-ms-contact',
    'coverage':'application/xml',
    'cpp':'text/plain',
    'crd':'application/x-mscardfile',
    'crl':'application/pkix-crl',
    'crt':'application/x-x509-ca-cert',
    'cs':'text/plain',
    'csdproj':'text/plain',
    'csproj':'text/plain',
    'csv':'text/csv',
    'cur':'application/octet-stream',
    'cxx':'text/plain',
    'dat':'application/octet-stream',
    'datasource':'application/xml',
    'dbproj':'text/plain',
    'def':'text/plain',
    'deploy':'application/octet-stream',
    'der':'application/x-x509-ca-cert',
    'dgml':'application/xml',
    'dib':'image/bmp',
    'dif':'video/x-dv',
    'disco':'text/xml',
    'dll.config':'text/xml',
    'dlm':'text/dlm',
    'docm':'application/vnd.ms-word.document.macroEnabled.12',
    'dot':'application/msword',
    'dotm':'application/vnd.ms-word.template.macroEnabled.12',
    'dotx':'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
    'dsp':'application/octet-stream',
    'dsw':'text/plain',
    'dtd':'text/xml',
    'dtsConfig':'text/xml',
    'dv':'video/x-dv',
    'dwf':'drawing/x-dwf',
    'dwp':'application/octet-stream',
    'eml':'message/rfc822',
    'emz':'application/octet-stream',
    'etl':'application/etl',
    'evy':'application/envoy',
    'exe.config':'text/xml',
    'fdf':'application/vnd.fdf',
    'fif':'application/fractals',
    'filters':'Application/xml',
    'fla':'application/octet-stream',
    'flr':'x-world/x-vrml',
    'fsscript':'application/fsharp-script',
    'fsx':'application/fsharp-script',
    'generictest':'application/xml',
    'group':'text/x-ms-group',
    'gsm':'audio/x-gsm',
    'gz':'application/x-gzip',
    'h':'text/plain',
    'hdml':'text/x-hdml',
    'hhc':'application/x-oleobject',
    'hhk':'application/octet-stream',
    'hhp':'application/octet-stream',
    'hlp':'application/winhlp',
    'hpp':'text/plain',
    'hta':'application/hta',
    'htc':'text/x-component',
    'htt':'text/webviewhtml',
    'hxa':'application/xml',
    'hxc':'application/xml',
    'hxd':'application/octet-stream',
    'hxe':'application/xml',
    'hxf':'application/xml',
    'hxh':'application/octet-stream',
    'hxi':'application/octet-stream',
    'hxk':'application/xml',
    'hxq':'application/octet-stream',
    'hxr':'application/octet-stream',
    'hxs':'application/octet-stream',
    'hxt':'text/html',
    'hxv':'application/xml',
    'hxw':'application/octet-stream',
    'hxx':'text/plain',
    'i':'text/plain',
    'ico':'image/x-icon',
    'ics':'application/octet-stream',
    'idl':'text/plain',
    'iii':'application/x-iphone',
    'inc':'text/plain',
    'inf':'application/octet-stream',
    'inl':'text/plain',
    'ins':'application/x-internet-signup',
    'ipa':'application/x-itunes-ipa',
    'ipg':'application/x-itunes-ipg',
    'ipproj':'text/plain',
    'ipsw':'application/x-itunes-ipsw',
    'iqy':'text/x-ms-iqy',
    'isp':'application/x-internet-signup',
    'ite':'application/x-itunes-ite',
    'itlp':'application/x-itunes-itlp',
    'itms':'application/x-itunes-itms',
    'itpc':'application/x-itunes-itpc',
    'IVF':'video/x-ivf',
    'jar':'application/java-archive',
    'java':'application/octet-stream',
    'jck':'application/liquidmotion',
    'jcz':'application/liquidmotion',
    'jfif':'image/pjpeg',
    'jnlp':'application/x-java-jnlp-file',
    'jpb':'application/octet-stream',
    'jsx':'text/jscript',
    'jsxbin':'text/plain',
    'library-ms':'application/windows-library+xml',
    'lit':'application/x-ms-reader',
    'loadtest':'application/xml',
    'lpk':'application/octet-stream',
    'lsf':'video/x-la-asf',
    'lst':'text/plain',
    'lsx':'video/x-la-asf',
    'm13':'application/x-msmediaview',
    'm14':'application/x-msmediaview',
    'm1v':'video/mpeg',
    'm2t':'video/vnd.dlna.mpeg-tts',
    'm2ts':'video/vnd.dlna.mpeg-tts',
    'm2v':'video/mpeg',
    'm4a':'audio/m4a',
    'm4b':'audio/m4b',
    'm4p':'audio/m4p',
    'm4r':'audio/x-m4r',
    'm4v':'video/x-m4v',
    'mac':'image/x-macpaint',
    'mak':'text/plain',
    'manifest':'application/x-ms-manifest',
    'map':'text/plain',
    'master':'application/xml',
    'mda':'application/msaccess',
    'mdb':'application/x-msaccess',
    'mde':'application/msaccess',
    'mdp':'application/octet-stream',
    'mfp':'application/x-shockwave-flash',
    'mht':'message/rfc822',
    'mhtml':'message/rfc822',
    'mix':'application/octet-stream',
    'mk':'text/plain',
    'mmf':'application/x-smaf',
    'mno':'text/xml',
    'mny':'application/x-msmoney',
    'mod':'video/mpeg',
    'mp2v':'video/mpeg',
    'mp4v':'video/mp4',
    'mpa':'video/mpeg',
    'mpf':'application/vnd.ms-mediapackage',
    'mpp':'application/vnd.ms-project',
    'mpv2':'video/mpeg',
    'mqv':'video/quicktime',
    'msi':'application/octet-stream',
    'mso':'application/octet-stream',
    'mts':'video/vnd.dlna.mpeg-tts',
    'mtx':'application/xml',
    'mvb':'application/x-msmediaview',
    'mvc':'application/x-miva-compiled',
    'mxp':'application/x-mmxp',
    'nsc':'video/x-ms-asf',
    'nws':'message/rfc822',
    'ocx':'application/octet-stream',
    'odc':'text/x-ms-odc',
    'odh':'text/plain',
    'odl':'text/plain',
    'odp':'application/vnd.oasis.opendocument.presentation',
    'ods':'application/oleobject',
    'odt':'application/vnd.oasis.opendocument.text',
    'one':'application/onenote',
    'onea':'application/onenote',
    'onepkg':'application/onenote',
    'onetmp':'application/onenote',
    'onetoc':'application/onenote',
    'onetoc2':'application/onenote',
    'orderedtest':'application/xml',
    'osdx':'application/opensearchdescription+xml',
    'p10':'application/pkcs10',
    'p12':'application/x-pkcs12',
    'p7b':'application/x-pkcs7-certificates',
    'p7c':'application/pkcs7-mime',
    'p7m':'application/pkcs7-mime',
    'p7r':'application/x-pkcs7-certreqresp',
    'p7s':'application/pkcs7-signature',
    'pcast':'application/x-podcast',
    'pct':'image/pict',
    'pcx':'application/octet-stream',
    'pcz':'application/octet-stream',
    'pfb':'application/octet-stream',
    'pfm':'application/octet-stream',
    'pfx':'application/x-pkcs12',
    'pic':'image/pict',
    'pict':'image/pict',
    'pkgdef':'text/plain',
    'pkgundef':'text/plain',
    'pko':'application/vnd.ms-pki.pko',
    'pls':'audio/scpls',
    'pma':'application/x-perfmon',
    'pmc':'application/x-perfmon',
    'pml':'application/x-perfmon',
    'pmr':'application/x-perfmon',
    'pmw':'application/x-perfmon',
    'pnt':'image/x-macpaint',
    'pntg':'image/x-macpaint',
    'pnz':'image/png',
    'pot':'application/vnd.ms-powerpoint',
    'potm':'application/vnd.ms-powerpoint.template.macroEnabled.12',
    'potx':'application/vnd.openxmlformats-officedocument.presentationml.template',
    'ppa':'application/vnd.ms-powerpoint',
    'ppam':'application/vnd.ms-powerpoint.addin.macroEnabled.12',
    'pps':'application/vnd.ms-powerpoint',
    'ppsm':'application/vnd.ms-powerpoint.slideshow.macroEnabled.12',
    'ppsx':'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
    'pptm':'application/vnd.ms-powerpoint.presentation.macroEnabled.12',
    'pptx':'application/vnd.openxmlformats-officedocument.presentationml.presentation',
    'prf':'application/pics-rules',
    'prm':'application/octet-stream',
    'prx':'application/octet-stream',
    'psc1':'application/PowerShell',
    'psd':'application/octet-stream',
    'psess':'application/xml',
    'psm':'application/octet-stream',
    'psp':'application/octet-stream',
    'pub':'application/x-mspublisher',
    'pwz':'application/vnd.ms-powerpoint',
    'qht':'text/x-html-insertion',
    'qhtm':'text/x-html-insertion',
    'qti':'image/x-quicktime',
    'qtif':'image/x-quicktime',
    'qtl':'application/x-quicktimeplayer',
    'qxd':'application/octet-stream',
    'rar':'application/octet-stream',
    'rat':'application/rat-file',
    'rc':'text/plain',
    'rc2':'text/plain',
    'rct':'text/plain',
    'rdlc':'application/xml',
    'resx':'application/xml',
    'rf':'image/vnd.rn-realflash',
    'rgs':'text/plain',
    'rmi':'audio/mid',
    'rmp':'application/vnd.rn-rn_music_package',
    'rqy':'text/x-ms-rqy',
    'ruleset':'application/xml',
    's':'text/plain',
    'safariextz':'application/x-safari-safariextz',
    'scd':'application/x-msschedule',
    'sct':'text/scriptlet',
    'sd2':'audio/x-sd2',
    'sdp':'application/sdp',
    'sea':'application/octet-stream',
    'searchConnector-ms':'application/windows-search-connector+xml',
    'setpay':'application/set-payment-initiation',
    'setreg':'application/set-registration-initiation',
    'settings':'application/xml',
    'sgimb':'application/x-sgimb',
    'shtml':'text/html',
    'sitemap':'application/xml',
    'skin':'application/xml',
    'sldm':'application/vnd.ms-powerpoint.slide.macroEnabled.12',
    'sldx':'application/vnd.openxmlformats-officedocument.presentationml.slide',
    'slk':'application/vnd.ms-excel',
    'sln':'text/plain',
    'slupkg-ms':'application/x-ms-license',
    'smd':'audio/x-smd',
    'smx':'audio/x-smd',
    'smz':'audio/x-smd',
    'snippet':'application/xml',
    'snp':'application/octet-stream',
    'sol':'text/plain',
    'sor':'text/plain',
    'spc':'application/x-pkcs7-certificates',
    'srf':'text/plain',
    'SSISDeploymentManifest':'text/xml',
    'ssm':'application/streamingmedia',
    'sst':'application/vnd.ms-pki.certstore',
    'stl':'application/vnd.ms-pki.stl',
    'svc':'application/xml',
    'testrunconfig':'application/xml',
    'testsettings':'application/xml',
    'tgz':'application/x-compressed',
    'thmx':'application/vnd.ms-officetheme',
    'thn':'application/octet-stream',
    'tlh':'text/plain',
    'tli':'text/plain',
    'toc':'application/octet-stream',
    'trm':'application/x-msterminal',
    'trx':'application/xml',
    'tts':'video/vnd.dlna.mpeg-tts',
    'u32':'application/octet-stream',
    'uls':'text/iuls',
    'user':'text/plain',
    'vb':'text/plain',
    'vbdproj':'text/plain',
    'vbk':'video/mpeg',
    'vbproj':'text/plain',
    'vbs':'text/vbscript',
    'vcf':'text/x-vcard',
    'vcproj':'Application/xml',
    'vcs':'text/plain',
    'vcxproj':'Application/xml',
    'vddproj':'text/plain',
    'vdp':'text/plain',
    'vdproj':'text/plain',
    'vdx':'application/vnd.ms-visio.viewer',
    'vml':'text/xml',
    'vscontent':'application/xml',
    'vsct':'text/xml',
    'vsd':'application/vnd.visio',
    'vsi':'application/ms-vsi',
    'vsix':'application/vsix',
    'vsixlangpack':'text/xml',
    'vsixmanifest':'text/xml',
    'vsmdi':'application/xml',
    'vspscc':'text/plain',
    'vss':'application/vnd.visio',
    'vsscc':'text/plain',
    'vssettings':'text/xml',
    'vssscc':'text/plain',
    'vst':'application/vnd.visio',
    'vstemplate':'text/xml',
    'vsto':'application/x-ms-vsto',
    'vsw':'application/vnd.visio',
    'vsx':'application/vnd.visio',
    'vtx':'application/vnd.visio',
    'wave':'audio/wav',
    'wax':'audio/x-ms-wax',
    'wbk':'application/msword',
    'wcm':'application/vnd.ms-works',
    'wdb':'application/vnd.ms-works',
    'wdp':'image/vnd.ms-photo',
    'webarchive':'application/x-safari-webarchive',
    'webtest':'application/xml',
    'wiq':'application/xml',
    'wiz':'application/msword',
    'wks':'application/vnd.ms-works',
    'WLMP':'application/wlmoviemaker',
    'wlpginstall':'application/x-wlpg-detect',
    'wlpginstall3':'application/x-wlpg3-detect',
    'wm':'video/x-ms-wm',
    'wma':'audio/x-ms-wma',
    'wmd':'application/x-ms-wmd',
    'wmf':'application/x-msmetafile',
    'wmp':'video/x-ms-wmp',
    'wmx':'video/x-ms-wmx',
    'wmz':'application/x-ms-wmz',
    'wpl':'application/vnd.ms-wpl',
    'wps':'application/vnd.ms-works',
    'wri':'application/x-mswrite',
    'wrz':'x-world/x-vrml',
    'wsc':'text/scriptlet',
    'wsdl':'text/xml',
    'wvx':'video/x-ms-wvx',
    'x':'application/directx',
    'xaf':'x-world/x-vrml',
    'xaml':'application/xaml+xml',
    'xap':'application/x-silverlight-app',
    'xbap':'application/x-ms-xbap',
    'xdr':'text/plain',
    'xla':'application/vnd.ms-excel',
    'xlam':'application/vnd.ms-excel.addin.macroEnabled.12',
    'xlc':'application/vnd.ms-excel',
    'xld':'application/vnd.ms-excel',
    'xlk':'application/vnd.ms-excel',
    'xll':'application/vnd.ms-excel',
    'xlm':'application/vnd.ms-excel',
    'xlsb':'application/vnd.ms-excel.sheet.binary.macroEnabled.12',
    'xlsm':'application/vnd.ms-excel.sheet.macroEnabled.12',
    'xlsx':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'xlt':'application/vnd.ms-excel',
    'xltm':'application/vnd.ms-excel.template.macroEnabled.12',
    'xltx':'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
    'xlw':'application/vnd.ms-excel',
    'xmta':'application/xml',
    'xof':'x-world/x-vrml',
    'XOML':'text/plain',
    'xps':'application/vnd.ms-xpsdocument',
    'xrm-ms':'text/xml',
    'xsc':'application/xml',
    'xsd':'text/xml',
    'xsf':'text/xml',
    'xslt':'text/xml',
    'xsn':'application/octet-stream',
    'xss':'application/xml',
    'xtp':'application/octet-stream',
    'z':'application/x-compress',
    /** origin */
    ez     : 'application/andrew-inset',
    hqx    : 'application/mac-binhex40',
    cpt    : 'application/mac-compactpro',
    doc    : 'application/msword',
    bin    : 'application/octet-stream',
    dms    : 'application/octet-stream',
    lha    : 'application/octet-stream',
    lzh    : 'application/octet-stream',
    exe    : 'application/octet-stream',
    class  : 'application/octet-stream',
    so     : 'application/octet-stream',
    dll    : 'application/octet-stream',
    oda    : 'application/oda',
    pdf    : 'application/pdf',
    ai     : 'application/postscript',
    eps    : 'application/postscript',
    ps     : 'application/postscript',
    smi    : 'application/smil',
    smil   : 'application/smil',
    mif    : 'application/vnd.mif',
    xls    : 'application/vnd.ms-excel',
    ppt    : 'application/vnd.ms-powerpoint',
    wbxml  : 'application/vnd.wap.wbxml',
    wmlc   : 'application/vnd.wap.wmlc',
    wmlsc  : 'application/vnd.wap.wmlscriptc',
    bcpio  : 'application/x-bcpio',
    vcd    : 'application/x-cdlink',
    pgn    : 'application/x-chess-pgn',
    cpio   : 'application/x-cpio',
    csh    : 'application/x-csh',
    dcr    : 'application/x-director',
    dir    : 'application/x-director',
    dxr    : 'application/x-director',
    dvi    : 'application/x-dvi',
    spl    : 'application/x-futuresplash',
    gtar   : 'application/x-gtar',
    hdf    : 'application/x-hdf',
    js     : 'application/x-javascript',
    skp    : 'application/x-koan',
    skd    : 'application/x-koan',
    skt    : 'application/x-koan',
    skm    : 'application/x-koan',
    latex  : 'application/x-latex',
    nc     : 'application/x-netcdf',
    cdf    : 'application/x-netcdf',
    sh     : 'application/x-sh',
    shar   : 'application/x-shar',
    swf    : 'application/x-shockwave-flash',
    sit    : 'application/x-stuffit',
    sv4cpio: 'application/x-sv4cpio',
    sv4crc : 'application/x-sv4crc',
    tar    : 'application/x-tar',
    tcl    : 'application/x-tcl',
    tex    : 'application/x-tex',
    texinfo: 'application/x-texinfo',
    texi   : 'application/x-texinfo',
    t      : 'application/x-troff',
    tr     : 'application/x-troff',
    roff   : 'application/x-troff',
    man    : 'application/x-troff-man',
    me     : 'application/x-troff-me',
    ms     : 'application/x-troff-ms',
    ustar  : 'application/x-ustar',
    src    : 'application/x-wais-source',
    xhtml  : 'application/xhtml+xml',
    xht    : 'application/xhtml+xml',
    zip    : 'application/zip',
    au     : 'audio/basic',
    snd    : 'audio/basic',
    mid    : 'audio/midi',
    midi   : 'audio/midi',
    kar    : 'audio/midi',
    mpga   : 'audio/mpeg',
    mp2    : 'audio/mpeg',
    mp3    : 'audio/mpeg',
    mp4    : 'video/mp4',
    aif    : 'audio/x-aiff',
    aiff   : 'audio/x-aiff',
    aifc   : 'audio/x-aiff',
    m3u    : 'audio/x-mpegurl',
    ram    : 'audio/x-pn-realaudio',
    rm     : 'audio/x-pn-realaudio',
    rpm    : 'audio/x-pn-realaudio-plugin',
    ra     : 'audio/x-realaudio',
    wav    : 'audio/x-wav',
    pdb    : 'chemical/x-pdb',
    xyz    : 'chemical/x-xyz',
    bmp    : 'image/bmp',
    gif    : 'image/gif',
    ief    : 'image/ief',
    jpeg   : 'image/jpeg',
    jpg    : 'image/jpeg',
    jpe    : 'image/jpeg',
    png    : 'image/png',
    tiff   : 'image/tiff',
    tif    : 'image/tiff',
    djvu   : 'image/vnd.djvu',
    djv    : 'image/vnd.djvu',
    wbmp   : 'image/vnd.wap.wbmp',
    ras    : 'image/x-cmu-raster',
    pnm    : 'image/x-portable-anymap',
    pbm    : 'image/x-portable-bitmap',
    pgm    : 'image/x-portable-graymap',
    ppm    : 'image/x-portable-pixmap',
    rgb    : 'image/x-rgb',
    xbm    : 'image/x-xbitmap',
    xpm    : 'image/x-xpixmap',
    xwd    : 'image/x-xwindowdump',
    igs    : 'model/iges',
    iges   : 'model/iges',
    msh    : 'model/mesh',
    mesh   : 'model/mesh',
    silo   : 'model/mesh',
    wrl    : 'model/vrml',
    vrml   : 'model/vrml',
    css    : 'text/css',
    html   : 'text/html',
    htm    : 'text/html',
    asc    : 'text/plain',
    txt    : 'text/plain',
    rtx    : 'text/richtext',
    rtf    : 'text/rtf',
    sgml   : 'text/sgml',
    sgm    : 'text/sgml',
    tsv    : 'text/tab-separated-values',
    wml    : 'text/vnd.wap.wml',
    wmls   : 'text/vnd.wap.wmlscript',
    etx    : 'text/x-setext',
    xsl    : 'text/xml',
    xml    : 'text/xml',
    mpeg   : 'video/mpeg',
    mpg    : 'video/mpeg',
    mpe    : 'video/mpeg',
    qt     : 'video/quicktime',
    mov    : 'video/quicktime',
    mxu    : 'video/vnd.mpegurl',
    avi    : 'video/x-msvideo',
    movie  : 'video/x-sgi-movie',
    ice    : 'x-conference/x-cooltalk',
    flv    : 'video/x-flv',
    m3u8   : 'application/x-mpegURL',
    ts     : 'video/MP2T',
    '3gp'  : 'video/3gpp',
    wmv    : 'video/x-ms-wmv'
};